name: otto-recommender
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - python>=3.7
  - numpy
  - pandas
  - scipy
  - scikit-learn==1.2
  - lightgbm==3.3.4
  - boto3
  - tqdm
  - more-itertools
  - plotly
  - tabulate
  - notebook
  - jupyter
  - ipynb-py-convert
  - pip:

